/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.bbn.openmap.app.OpenMap;
import com.bbn.openmap.gui.OpenMapFrame;
import com.bbn.openmap.layer.shape.ShapeLayer;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jorge F
 */
public class frmAdminSimulacion extends OpenMapFrame {

    /**
     * Creates new form frmAdminSimulacion
     */
    public frmAdminSimulacion() {
        super("Simple Map");
        initComponents();
        initMap();
    }

    private void initMap(){
        Properties shapeLayerProps = new Properties();
        /*InputStream is = null;
        try {
           is = new FileInputStream("Properties.properties");
           shapeLayerProps.load(is);
        } catch (FileNotFoundException ex) {
           Logger.getLogger(OpenMap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           Logger.getLogger(OpenMap.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
           if (is != null) {
              try {
                 is.close();
              } catch (IOException ex) {
                Logger.getLogger(OpenMap.class.getName()).log(Level.SEVERE, null, ex);
              }
           }
        }*/
          shapeLayerProps.put("prettyName", "Political Solid");
          shapeLayerProps.put("lineColor", "000000");
          shapeLayerProps.put("fillColor", "BDDE83");
          shapeLayerProps.put("shapeFile", "resources/map/shape/dcwpo-browse.shp");
          shapeLayerProps.put("spatialIndex", "resources/map/shape/dcwpo-browse.ssx");

          ShapeLayer shapeLayer = new ShapeLayer();
          shapeLayer.setProperties(shapeLayerProps);

          // Add the political layer to the map
          mapPanel.getMapBean().add(shapeLayer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new com.bbn.openmap.gui.BasicMapPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(mapPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bbn.openmap.gui.BasicMapPanel mapPanel;
    // End of variables declaration//GEN-END:variables
}
