/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.bbn.openmap.Environment;
import com.bbn.openmap.MapHandler;
import com.bbn.openmap.PropertyHandler;
import com.bbn.openmap.app.OpenMap;
import com.bbn.openmap.gui.BasicMapPanel;
import com.bbn.openmap.gui.OpenMapFrame;
import com.bbn.openmap.layer.shape.ShapeLayer;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author Jorge F
 */
public class frmAdminSimulacion extends OpenMapFrame {

    /**
     * Creates new form frmAdminSimulacion
     */
    public frmAdminSimulacion() {
        super("Simple Map");
        initComponents();
        //initMap();
    }

    /*private void initMap(){
        Properties shapeLayerProps = new Properties();
        PropertyHandler propertyHandler = null;
        try {
           propertyHandler = new PropertyHandler.Builder().setPropertiesFile("./openmap.properties").build();
        } catch (IOException ex) {
            Logger.getLogger(frmAdminSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShapeLayer shapeLayer = new ShapeLayer();
        if (propertyHandler != null) {
           shapeLayer.setProperties(propertyHandler.getProperties());
        }

        // Add the political layer to the map
        mapPanel.getMapBean().add(shapeLayer);
        
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openMap1 = new Vista.OpenMap();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
            
            SwingUtilities.invokeLater(() -> {
            Vista.OpenMap.create("./openmap.properties").showInFrame();
        });
            
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminSimulacion().setVisible(true);
            }
        });
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.OpenMap openMap1;
    // End of variables declaration//GEN-END:variables
}
