/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.VueloBL;
import Modelo.Vuelo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author JUAN
 */
public class frmBuscarVuelo extends javax.swing.JDialog {

    private ArrayList<Vuelo>lstVuelos=new ArrayList<Vuelo>();
    private ArrayList<Vuelo> filter = new ArrayList<Vuelo>();
    private VueloBL controlador = new VueloBL();
    //private frmReporteVuelo
    //private frmReporteVuelo panelVuelo=null;
    /**
     * Creates new form frmBuscarVuelo
     */
    public frmBuscarVuelo(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        this.setResizable(false);
    }
    
    public frmBuscarVuelo(java.awt.Frame parent, boolean modal, frmReportePaquete panel) {
        super(parent, modal);
        initComponents();
        //this.panelPaq = panel;
        lstVuelos = controlador.listaVuelos();
        DefaultTableModel model = (DefaultTableModel)tblVuelo.getModel();
        for(int i=0; i<lstVuelos.size(); i++){
            Object[] obj = new Object[3];
            obj[0] = lstVuelos.get(i).getCodigo();
            obj[1] = lstVuelos.get(i).getAeropuertoOrigen() + " -> " + lstVuelos.get(i).getAeropuertoDestino();
            obj[2] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(lstVuelos.get(i).getFechaSalida());
            obj[3] = lstVuelos.get(i).getCapActual();
            obj[4] = lstVuelos.get(i).getCapMax();
            model.addRow(obj);
        }
        filter = lstVuelos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelo = new javax.swing.JTable();
        btnSelec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BUSCAR VUELO");

        tblVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Origen -> Destino", "Fecha Salida", "Capacidad Máxima"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVuelo);

        btnSelec.setText("Seleccionar");
        btnSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(9, 9, 9)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(btnSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelec))
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("BUSCAR VUELO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        String parametro = txtNombre.getText() + String.valueOf(evt.getKeyChar());
        DefaultTableModel model = (DefaultTableModel)tblVuelo.getModel();
        while(tblVuelo.getRowCount() > 0)
        model.removeRow(0);
        filter = new ArrayList<Vuelo>();
        if(!(((txtNombre.getText().length() == 1) || (txtNombre.getText().length() == 0)) &&
            ((evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE)))){
            for(int i=0; i<lstVuelos.size(); i++){
                if(lstVuelos.get(i).getCodigo().toLowerCase().contains(parametro))
                filter.add(lstVuelos.get(i));
            }
        }
        else filter = lstVuelos;
        for(int i=0; i<filter.size(); i++){
            Object[] obj = new Object[3];
            obj[0] = filter.get(i).getCodigo();
            obj[1] = filter.get(i).getAeropuertoDestino() + " -> " + filter.get(i).getAeropuertoOrigen();
            obj[2] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(filter.get(i).getFechaSalida());
            obj[3] = lstVuelos.get(i).getCapActual();
            obj[4] = lstVuelos.get(i).getCapMax();
            model.addRow(obj);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecActionPerformed
        if(tblVuelo.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,
            "Debe seleccionar un aeropuerto de la tabla primero",
            "Mensaje de error", JOptionPane.INFORMATION_MESSAGE);
        else{
            //panelPaq.setCodigo(filter.get(tblVuelo.getSelectedRow()).getCodigo());
            this.dispose();
        }
    }//GEN-LAST:event_btnSelecActionPerformed

                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarVuelo dialog = new frmBuscarVuelo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVuelo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
